name: Continuous Integration Pipeline

on: [push, pull_request]

jobs:
  check_style_backend:
    runs-on: ubuntu-latest
    container: gradle:7.5-jdk17
    steps:
      - uses: actions/checkout@v2
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            bank_system_backend/.gradle/wrapper
            bank_system_backend/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Check Style for Backend
        run: |
          cd bank_system_backend
          gradle checkstyleMain checkstyleTest checkstyleIntegration

  check_style_frontend:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v2
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: bank_system_frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Check Style for Frontend
        run: |
          cd bank_system_frontend
          npm ci
          npm run lint

  build_backend:
    runs-on: ubuntu-latest
    container: gradle:7.5-jdk17
    needs: check_style_backend
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend
        run: |
          cd bank_system_backend
          gradle assemble

  build_frontend:
    runs-on: ubuntu-latest
    container: node:18
    needs: check_style_frontend
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          cd bank_system_frontend
          npm ci
          npm run build

  test_unit_backend:
    runs-on: ubuntu-latest
    container: gradle:7.5-jdk17
    needs: build_backend
    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests for Backend
        run: |
          cd bank_system_backend
          gradle unitTest

  test_integration_backend:
    runs-on: ubuntu-latest
    container: gradle:7.5-jdk17
    needs: test_unit_backend
    steps:
      - uses: actions/checkout@v2
      - name: Integration Tests for Backend
        run: |
          cd bank_system_backend
          gradle integrationTest
